services:
  postgres:
    image: postgres:15
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: evouser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: evolutiondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"

  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances
  llm:
    build: ./llm
    container_name: keeper-llm
    restart: always
    env_file:
      - .env

  keeper-service:
    build: ./keeper-service
    container_name: keeper-service
    restart: always
    env_file:
      - .env
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/app/key/keeper-buddy-eac2edfeddc3.json

  dispatcher:
    build: ./dispatcher
    container_name: keeper-dispatcher
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - llm
      - keeper-service
      - evolution-api

volumes:
  postgres_data:
  evolution_instances: